### ISSUE TITLE
Improve main-site web performance

### ISSUE THREAD

**Issue by simoneduca** [dwp/design-system#372]
Analyse both desktop and mobile performance (the latter is worse).
Look into integrating PageSpeed Insights in the site architecture.

**Comment by jonhurrell** [comment]
There's the load lag which is a persistent issue to add here.

**Comment by htmlandbacon** [comment]
Just on update on this as I think we've made a few gains - just as an outline

1. Optimised assets for deployment (280kb) down to 50kb)
2. Optimised node app run mode and moved asset build to the CI
3. Removed unneeded file io calls
4. Switched code render to markdown

There is still options for being more choices to come but we can review that when we have a bit more of a path for the frontend.

| Versions            | 2.5% latency | 50% latency | Avg  | 1% Req/sec | 50% Req/Sec | Avg   |
|---------------------|--------------|-------------|------|------------|-------------|-------|
| Base                | 171          | 801         | 885  | 9          | 11          | 11.07 |
| With render changes (next release) | 57           | 61          | 68   | 113        | 146         | 145   |
| Super cached        | 11           | 15          | 18.5 | 284        | 512         | 526   |

Assumption is in AWS this profile will look different due to network latency and not being dev machine

## Tools use

- [autocannon](https://www.npmjs.com/package/autocannon) for cheap load testing
- [lighthouse](https://developer.chrome.com/docs/lighthouse/overview)
- AWS monitoring
