### ISSUE TITLE
Find my address by postcode/house number

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#404]
## What
Improve the postcode look up as shown in GDS design system ( https://design-system.service.gov.uk/patterns/addresses/)

### Example: 
<img width="845" alt="Screen Shot 2019-06-19 at 17 25 51" src="https://user-images.githubusercontent.com/4334015/59783111-525ce180-92b7-11e9-9fd4-d7fb140ee8aa.png">

## Why 
Avoid giving the user a long list of addresses. 

#### Services

- Budgeting loans

**Original issue information** 19 June 2019 @htmlandbacon https://github.com/dwp/design-examples/issues/41

**Comment by steven-borthwick** [comment]
<img width="1127" alt="Screen Shot 2020-02-22 at 13 43 35" src="https://user-images.githubusercontent.com/12656517/75093447-b7b94e80-5579-11ea-8093-c35e18d5a2b8.png">

There were some issues with the "Property Number or name" field in user research.

- 7/7 non-UK participants entered the street name in addition to the property number
- One UK participant in usability testing entered their house name only, which is the expected behaviour
- Our hypothesis is that using name is prompting non-UK participants to enter their whole address, as ‘house name’ is not widely recognised. 
- Nobody questioned use of the word ‘Property’ in ’Property number or name

Needs further research.

**Comment by htmlandbacon** [comment]
> <img alt="Screen Shot 2020-02-22 at 13 43 35" width="1127" src="https://user-images.githubusercontent.com/12656517/75093447-b7b94e80-5579-11ea-8093-c35e18d5a2b8.png">
> 
> There were some issues with the "Property Number or name" field in user research.
> 
> * 7/7 non-UK participants entered the street name in addition to the property number
> * One UK participant in usability testing entered their house name only, which is the expected behaviour
> * Our hypothesis is that using name is prompting non-UK participants to enter their whole address, as ‘house name’ is not widely recognised.
> * Nobody questioned use of the word ‘Property’ in ’Property number or name
> 
> Needs further research.

Oh, interesting, is there a td-lr to what this was against?

**Comment by htmlandbacon** [comment]
<img width="1284" alt="example of home and correspondance address lookup form child maintenance apply service" src="https://user-images.githubusercontent.com/4334015/113126546-abd59c80-920f-11eb-84e7-7bff2abb6ada.png">

I took this out of the December build for the child maintenance service but may have some refinement on top (@benraine)

Couple of things:

- [Labels where updated as some people didn't know what we where asking vs standard pattern](https://github.com/alphagov/govuk-design-system-backlog/issues/31#issuecomment-614733303), @abbott567 has also flagged some Dragon issues with the original version
- The order of this was flipped to give more reassurance to people when giving there home address
- We didn't replay the search
- We didn't give notice of nothing returned from the address search, we just bounced them to manual address

With the additional intent of letters there is probably a second bit for completeness around formats.

[Pension Credit have an example of contact formats](https://github.com/dwp/design-system/issues/426).

**Comment by jonhurrell** [comment]
Closing this as epic moved into the [roadmap](https://github.com/dwp/design-system/issues/237).
