### ISSUE TITLE
Bundle static files for cookie banner UI (Nunjucks/SCSS/Tests) and publish to DWP Engineering NPM

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#53]
**Is your feature request related to a problem? Please describe.**
The cookies banner UI needs bundling via NPM to allow services and designers prototyping (using same stack) to quickly implement part of the pattern. 

  **Describe the solution you'd like**
All code and related tests for the cookies banner UI to be package managed via nom, using the DWP Engineering account 

  **Additional context**
Review the publishing guidelines by engineering practice.
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by simoneduca** [comment]
I've set up gulp tasks and express in dwp-frontend to generate a `package` folder, which will be the one published to npm. Very much in the same vein as govuk-frontend.

**Comment by simoneduca** [comment]
So it looks like things have changed slightly since last time I talked to Adam about publishing to dwp npm. Anything we want to push to that registry, now has to piped through a [Docker image](https://gitlab.nonprod.dwpcloud.uk/engineering-practice/publish-source-code) that replaces/deletes all the sensitive data before making the code public. I'm waiting on Mike or James to get back to me and show me how to do it. I will try to have a go myself tomorrow either way.

**Comment by simoneduca** [comment]
Access to Nexus requested on 12/11 https://jira.service.dwpcloud.uk/servicedesk/customer/portal/6/SRVC-37382
Will update here.

**Comment by simoneduca** [comment]
Update: We have access to Nexus, which means we can push a package to the dwp npm nexus proxy... in order to publish to the npm public registry we need to pass this checklist https://confluence.service.dwpcloud.uk/pages/viewpage.action?spaceKey=EN&title=Guidance+on+creating+open+source+products and get our npm account to the dwp scope.

**Comment by simoneduca** [comment]
Update: pushing to nexus wasn't straightforward(!), but `dwp-frontend` has now been published on Nexus and can be installed from there. Next step: publish to npm public registry.

**Comment by simoneduca** [comment]
Update: before open-sourcing, we'll have to go through the steps on Confluence with another engineer. We also need to put the app through https://gitlab.nonprod.dwpcloud.uk/engineering-practice/publish-source-code to remove anything unnecessary.
