### ISSUE TITLE
Gather any insights from existing or planned user research

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#61]
**Is your feature request related to a problem? Please describe.**
As part of assurance for any pattern we need to make sure we have a insights from user research.

**Describe the solution you'd like**
Either we reach out to service teams currently the consent to cookies pattern (Child Maintenance) or we ask the other Leads to help identify a service which can help support us.

 **Additional context**
[This relates to the consent to cookies epic](https://github.com/dwp/design-system/issues/44)

**Comment by HelenOsg** [comment]
Spoke to Colin Oakley to find out what research/insight could be shared. Insights shared:
- 80-90% opt in but majority of traffic comes through mobile. Is this high opt in rate due to the design on mobile (takes over the screen meaning)?
No noticeable increase in drop outs since implementing the design but more data needed.
Small page views on cookie policy and details pages.

Agreed to send list of questions for service team to look in to and to contact Catherine Hope for analytics information. 
Current question list:
Performance analyst questions
How many users are visiting the policy and details pages? 
Do you have the numbers of people updating their settings after opting in/out? 
Has there been any impact on users dropping out of the service since putting the cookie pattern in?
Opt in rates for different devices


UR questions
Do users understand what they are consenting to?
Any anxiety/hesitation about consenting to cookies?
Impact of current design on mobile users

**Comment by HelenOsg** [comment]
Request with service team and Catherine for insight.
Include in the information on the page the gaps in research so other service teams can help support improving the pattern.

**Comment by HelenOsg** [comment]
Update from Catherine on GA from Apply for help arranging child maintenance:


Device Category | Users | Sessions
-- | -- | --
desktop | 760 | 1,008
mobile | 4,041 | 6,615
tablet | 68 | 96

Users = someone on the same device. Sessions=each time they visit the site on that device. We get lots of one page visits from where people have timed out and interact with the browser again
 
I looked at the cookies page usage for all time. We put GA back onto the service on 4 March.
Of the 56,600 sessions 4 March - 4 November, there were 110 unique views of the cookies page and 9 unique views of the cookies details page.
On the cookies page there were 23 clicks of the No answer in the consent question, 6 clicks of Yes.
 
So VERY little traffic and interaction with the cookies content.

Question: Looking at the numbers of users and sessions they are significantly more mobile than desktop. Is that representative of what we see for all users across services or do we think have higher opt in rates for mobile users?

We think it’s both – that the service gets mainly mobile AND that the opt-in rate is higher.
 
You’ll need to get data from the logs to compare the actual results to the GA ones. Colin Oakley might be able to help with that.

**Comment by HelenOsg** [comment]
Next steps:
Ask Colin for data from logs on total sessions from 5 October to 1 November
Find out other service user device split

**Comment by HelenOsg** [comment]
Data from Kibana logs
but over the last 30 days according to Kibana, it's 2482 URNs
and according to GA over the last 30 days 2025 have completed the URN goal

81% opt in for cookies. Of that 82% of traffic is from mobile.
